# Site settings
title: Website
email:
description: Main website for Dzu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dpham17.github.io" # the base hostname & protocol for your site
# twitter_username: username
github_username: dpham17
last_update: March 30, 2017

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks", "MathJax"]
